const userData = {
  name: "Kenny Ray",
  email: "kenny76@gmail.com",
  avatar: "https://www.loremfaces.net/96/id/3.jpg",
};

const jobs = [
  {
    id: "job_001",
    title: "Mow the Lawn",
    description:
      "Need someone to mow my small compound lawn this Saturday morning.",
    category: "Gardening",
    payAmount: 3000,
    currency: "NGN",
    status: "open",
    location: {
      state: "Lagos",
      city: "Surulere",
      address: "11 Ogunlana Drive",
      lat: 6.5055,
      lng: 3.3565,
    },
    poster: {
      id: "usr_001",
      name: "Tunde Ajayi",
      rating: 4.8,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    preferredTimeWindow: { from: "08:00", to: "11:00" },
    createdAt: "2025-10-29T08:20:00Z",
  },
  {
    id: "job_002",
    title: "Wash Car",
    description: "Need car washed and cleaned inside out.",
    category: "Cleaning",
    payAmount: 1500,
    currency: "NGN",
    status: "completed",
    location: {
      state: "Abuja",
      city: "Garki",
      address: "Plot 14, Area 3",
      lat: 9.033,
      lng: 7.495,
    },
    poster: {
      id: "usr_002",
      name: "Ngozi Peters",
      rating: 4.6,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/24.jpg",
    },
    createdAt: "2025-10-28T09:00:00Z",
  },
  {
    id: "job_003",
    title: "Help Move Furniture",
    description:
      "Need two people to help move furniture to another flat in same building.",
    category: "Manual Labor",
    payAmount: 5000,
    currency: "NGN",
    status: "in_progress",
    location: {
      state: "Oyo",
      city: "Ibadan",
      address: "Mokola Roundabout",
      lat: 7.395,
      lng: 3.896,
    },
    poster: {
      id: "usr_003",
      name: "Ibrahim Yusuf",
      rating: 4.2,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    createdAt: "2025-10-28T13:15:00Z",
  },
  {
    id: "job_004",
    title: "Water the Plants",
    description: "Need someone to water and prune flowers twice a week.",
    category: "Gardening",
    payAmount: 2000,
    currency: "NGN",
    status: "open",
    location: {
      state: "Lagos",
      city: "Ikeja",
      address: "12 Oba Akran Avenue",
      lat: 6.6018,
      lng: 3.3515,
    },
    poster: {
      id: "usr_004",
      name: "Bisi Olatunji",
      rating: 4.9,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    createdAt: "2025-10-27T07:45:00Z",
  },
  {
    id: "job_005",
    title: "Clean Small Office",
    description:
      "Sweep and mop a 2-room office. Shouldn’t take more than 1 hour.",
    category: "Cleaning",
    payAmount: 2500,
    currency: "NGN",
    status: "open",
    location: {
      state: "Rivers",
      city: "Port Harcourt",
      address: "Old GRA, Aba Road",
      lat: 4.806,
      lng: 7.018,
    },
    poster: {
      id: "usr_005",
      name: "Chinedu Okafor",
      rating: 4.7,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/34.jpg",
    },
    createdAt: "2025-10-28T15:30:00Z",
  },
  {
    id: "job_006",
    title: "Deliver Groceries",
    description:
      "Pick up groceries from Next Cash and Carry and deliver to Wuse Zone 4.",
    category: "Delivery",
    payAmount: 3000,
    currency: "NGN",
    status: "in_progress",
    location: {
      state: "Abuja",
      city: "Wuse",
      address: "Zone 4, Wuse",
      lat: 9.064,
      lng: 7.478,
    },
    poster: {
      id: "usr_006",
      name: "Aisha Bello",
      rating: 4.5,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    createdAt: "2025-10-29T11:00:00Z",
  },
  {
    id: "job_007",
    title: "Walk a Dog",
    description: "Friendly Labrador needs daily evening walks for one week.",
    category: "Pet Care",
    payAmount: 4000,
    currency: "NGN",
    status: "completed",
    location: {
      state: "Lagos",
      city: "Lekki",
      address: "Admiralty Way",
      lat: 6.45,
      lng: 3.472,
    },
    poster: {
      id: "usr_007",
      name: "Ify Nwachukwu",
      rating: 4.9,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/18.jpg",
    },
    createdAt: "2025-10-26T17:20:00Z",
  },
  {
    id: "job_008",
    title: "Repair Electric Socket",
    description: "One socket not working properly in bedroom.",
    category: "Electrical",
    payAmount: 2500,
    currency: "NGN",
    status: "open",
    location: {
      state: "Enugu",
      city: "Independence Layout",
      address: "Chime Avenue",
      lat: 6.439,
      lng: 7.503,
    },
    poster: {
      id: "usr_008",
      name: "Emeka Ibe",
      rating: 4.3,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    createdAt: "2025-10-29T09:40:00Z",
  },
  {
    id: "job_009",
    title: "Paint Small Gate",
    description: "Need someone to repaint a metal gate. Paint provided.",
    category: "Handyman",
    payAmount: 3500,
    currency: "NGN",
    status: "completed",
    location: {
      state: "Delta",
      city: "Warri",
      address: "Enerhen Junction",
      lat: 5.519,
      lng: 5.757,
    },
    poster: {
      id: "usr_009",
      name: "Faith Oghene",
      rating: 4.6,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/39.jpg",
    },
    createdAt: "2025-10-27T11:10:00Z",
  },
  {
    id: "job_010",
    title: "Wash Clothes",
    description: "Need help washing and drying a small load of clothes.",
    category: "Domestic",
    payAmount: 2000,
    currency: "NGN",
    status: "open",
    location: {
      state: "Kano",
      city: "Kano City",
      address: "Sabon Gari Market",
      lat: 12.001,
      lng: 8.517,
    },
    poster: {
      id: "usr_010",
      name: "Halima Sani",
      rating: 4.4,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/43.jpg",
    },
    createdAt: "2025-10-28T08:00:00Z",
  },
  {
    id: "job_011",
    title: "Fix Broken Chair",
    description: "Wooden dining chair needs repair; one leg loose.",
    category: "Carpentry",
    payAmount: 1800,
    currency: "NGN",
    status: "completed",
    location: {
      state: "Anambra",
      city: "Awka",
      address: "Zik Avenue",
      lat: 6.21,
      lng: 7.074,
    },
    poster: {
      id: "usr_011",
      name: "Uchenna Okeke",
      rating: 4.7,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/38.jpg",
    },
    createdAt: "2025-10-25T14:25:00Z",
  },
  {
    id: "job_012",
    title: "Run Errand to Market",
    description:
      "Buy vegetables and tomatoes at Bodija Market and deliver nearby.",
    category: "Errand",
    payAmount: 1500,
    currency: "NGN",
    status: "in_progress",
    location: {
      state: "Oyo",
      city: "Ibadan",
      address: "Bodija Market",
      lat: 7.442,
      lng: 3.899,
    },
    poster: {
      id: "usr_012",
      name: "Kehinde Adebayo",
      rating: 4.5,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/42.jpg",
    },
    createdAt: "2025-10-28T16:10:00Z",
  },
  {
    id: "job_013",
    title: "Clean Water Tank",
    description:
      "Water tank needs washing and disinfecting. Must have proper tools.",
    category: "Cleaning",
    payAmount: 5000,
    currency: "NGN",
    status: "open",
    location: {
      state: "Kaduna",
      city: "Barnawa",
      address: "Near NNPC filling station",
      lat: 10.496,
      lng: 7.441,
    },
    poster: {
      id: "usr_013",
      name: "Abdulraman Lawal",
      rating: 4.1,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/40.jpg",
    },
    createdAt: "2025-10-29T06:55:00Z",
  },
  {
    id: "job_014",
    title: "Polish Shoes",
    description: "Need shoes polished for an event tomorrow morning.",
    category: "Personal Service",
    payAmount: 1000,
    currency: "NGN",
    status: "completed",
    location: {
      state: "Lagos",
      city: "Yaba",
      address: "Commercial Avenue",
      lat: 6.515,
      lng: 3.386,
    },
    poster: {
      id: "usr_014",
      name: "Oluwaseun Taiwo",
      rating: 4.8,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    },
    createdAt: "2025-10-28T19:10:00Z",
  },
  {
    id: "job_015",
    title: "Assemble Shelf",
    description:
      "Flat-pack shelf needs assembling. Should take about 30 minutes.",
    category: "Handyman",
    payAmount: 3500,
    currency: "NGN",
    status: "open",
    location: {
      state: "Edo",
      city: "Benin City",
      address: "Ugbowo Road",
      lat: 6.339,
      lng: 5.617,
    },
    poster: {
      id: "usr_015",
      name: "Blessing Omo",
      rating: 4.6,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/56.jpg",
    },
    createdAt: "2025-10-29T07:30:00Z",
  },
];

const jobCategories = [
  {
    id: "cat_001",
    name: "Cleaning",
    description:
      "Jobs that involve tidying, sweeping, or washing spaces or items.",
    examples: [
      "Clean small office",
      "Wash car",
      "Wash clothes",
      "Clean water tank",
    ],
  },
  {
    id: "cat_002",
    name: "Gardening",
    description:
      "Outdoor and plant-related work such as trimming, watering, or mowing.",
    examples: ["Mow the lawn", "Water the plants", "Trim hedges"],
  },
  {
    id: "cat_003",
    name: "Delivery",
    description:
      "Picking up and delivering small packages or errands around town.",
    examples: ["Deliver groceries", "Pick up parcels", "Run market errands"],
  },
  {
    id: "cat_004",
    name: "Manual Labor",
    description:
      "Physically intensive short-term work like lifting or moving items.",
    examples: ["Help move furniture", "Carry goods", "Load or unload truck"],
  },
  {
    id: "cat_005",
    name: "Handyman",
    description:
      "Fixing, repairing, or assembling items around homes or offices.",
    examples: ["Fix broken chair", "Assemble shelf", "Paint small gate"],
  },
  {
    id: "cat_006",
    name: "Electrical",
    description:
      "Simple electrical jobs that require minor technical knowledge.",
    examples: ["Repair socket", "Install bulb", "Fix light switch"],
  },
  {
    id: "cat_007",
    name: "Carpentry",
    description: "Woodwork-related jobs like furniture repair or fabrication.",
    examples: ["Fix table leg", "Polish wooden shelf", "Repair door frame"],
  },
  {
    id: "cat_008",
    name: "Domestic Help",
    description: "Small household tasks and chores done occasionally.",
    examples: ["Wash dishes", "Sweep compound", "Iron clothes"],
  },
  {
    id: "cat_009",
    name: "Pet Care",
    description: "Taking care of animals or performing pet-related tasks.",
    examples: ["Walk dog", "Feed cat", "Clean pet cage"],
  },
  {
    id: "cat_010",
    name: "Errands",
    description:
      "Quick, short tasks that involve running small errands nearby.",
    examples: ["Buy vegetables", "Collect item", "Drop documents"],
  },
  {
    id: "cat_011",
    name: "Personal Service",
    description: "Individual-focused services or grooming-related activities.",
    examples: ["Polish shoes", "Do makeup", "Style hair"],
  },
  {
    id: "cat_012",
    name: "Tech Help",
    description: "Basic technical support for phones, laptops, or gadgets.",
    examples: ["Install app", "Fix WiFi issue", "Set up printer"],
  },
  {
    id: "cat_013",
    name: "Tutoring",
    description: "Short-term teaching or helping with academic work.",
    examples: [
      "Help with math homework",
      "Teach basic English",
      "Tutor child for exam",
    ],
  },
  {
    id: "cat_014",
    name: "Event Assistance",
    description: "Help with setup, coordination, or cleanup during events.",
    examples: ["Serve drinks", "Arrange chairs", "Decorate hall"],
  },
  {
    id: "cat_015",
    name: "Other",
    description:
      "Miscellaneous small jobs that don’t fit any specific category.",
    examples: ["Hold place in queue", "Run simple survey", "Assist elderly"],
  },
];

const locations = [
  {
    state: "Lagos",
    cities: [
      "Ikeja",
      "Surulere",
      "Lekki",
      "Yaba",
      "Victoria Island",
      "Ajah",
      "Ikorodu",
    ],
  },
  {
    state: "Abuja (FCT)",
    cities: ["Wuse", "Garki", "Maitama", "Asokoro", "Gwarinpa", "Utako"],
  },
  {
    state: "Oyo",
    cities: ["Ibadan", "Ogbomoso", "Oyo Town", "Saki", "Eruwa"],
  },
  {
    state: "Rivers",
    cities: ["Port Harcourt", "Obio-Akpor", "Oyigbo", "Bonny", "Omoku"],
  },
  {
    state: "Edo",
    cities: ["Benin City", "Ekpoma", "Auchi", "Uromi"],
  },
  {
    state: "Anambra",
    cities: ["Awka", "Onitsha", "Nnewi", "Ekwulobia"],
  },
  {
    state: "Delta",
    cities: ["Warri", "Asaba", "Sapele", "Ughelli"],
  },
  {
    state: "Kano",
    cities: ["Kano City", "Gwale", "Tarauni", "Nasarawa", "Fagge"],
  },
  {
    state: "Kaduna",
    cities: ["Kaduna North", "Kaduna South", "Barnawa", "Zaria", "Kafanchan"],
  },
  {
    state: "Enugu",
    cities: ["Enugu City", "Nsukka", "Independence Layout", "Awgu"],
  },
  {
    state: "Ogun",
    cities: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota"],
  },
  {
    state: "Osun",
    cities: ["Osogbo", "Ile-Ife", "Ilesa", "Ede"],
  },
  {
    state: "Ekiti",
    cities: ["Ado-Ekiti", "Ikere-Ekiti", "Iyin-Ekiti"],
  },
  {
    state: "Kwara",
    cities: ["Ilorin", "Offa", "Omu-Aran"],
  },
  {
    state: "Imo",
    cities: ["Owerri", "Okigwe", "Orlu"],
  },
  {
    state: "Akwa Ibom",
    cities: ["Uyo", "Eket", "Ikot Ekpene", "Oron"],
  },
  {
    state: "Cross River",
    cities: ["Calabar", "Ikom", "Ogoja"],
  },
  {
    state: "Plateau",
    cities: ["Jos", "Barkin Ladi", "Pankshin"],
  },
  {
    state: "Benue",
    cities: ["Makurdi", "Gboko", "Otukpo"],
  },
  {
    state: "Niger",
    cities: ["Minna", "Bida", "Kontagora"],
  },
];

const WAL_BAL = 5000;

const sentApplicationsList = [
  {
    id: "job_001",
    title: "Mow the Lawn",
    description:
      "Need someone to mow my small compound lawn this Saturday morning.",
    category: "Gardening",
    payAmount: 3000,
    currency: "NGN",
    // status: "open",
    location: {
      state: "Lagos",
      city: "Surulere",
      address: "11 Ogunlana Drive",
      lat: 6.5055,
      lng: 3.3565,
    },
    status: "pending",
    poster: {
      id: "usr_001",
      name: "Tunde Ajayi",
      rating: 4.8,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/11.jpg",
    },
    preferredTimeWindow: { from: "08:00", to: "11:00" },
    createdAt: "2025-10-29T08:20:00Z",
  },
  {
    id: "job_002",
    title: "Wash Car",
    description: "Need car washed and cleaned inside out.",
    category: "Cleaning",
    payAmount: 1500,
    currency: "NGN",
    // status: "completed",
    location: {
      state: "Abuja",
      city: "Garki",
      address: "Plot 14, Area 3",
      lat: 9.033,
      lng: 7.495,
    },
    status: "accepted",
    poster: {
      id: "usr_002",
      name: "Ngozi Peters",
      rating: 4.6,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/women/24.jpg",
    },
    createdAt: "2025-10-28T09:00:00Z",
  },
  {
    id: "job_003",
    title: "Help Move Furniture",
    description:
      "Need two people to help move furniture to another flat in same building.",
    category: "Manual Labor",
    payAmount: 5000,
    currency: "NGN",
    // status: "in_progress",
    location: {
      state: "Oyo",
      city: "Ibadan",
      address: "Mokola Roundabout",
      lat: 7.395,
      lng: 3.896,
    },
    status: "rejected",
    poster: {
      id: "usr_003",
      name: "Ibrahim Yusuf",
      rating: 4.2,
      phoneVerified: true,
      photoUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    createdAt: "2025-10-28T13:15:00Z",
  },
];

const applicants = [
  {
    id: "1",
    name: "Kelly",
    image: "https://www.loremfaces.net/96/id/1.jpg",
  },
  {
    id: "2",
    name: "Alfred",
    image: "https://www.loremfaces.net/96/id/2.jpg",
  },
  {
    id: "3",
    name: "Ken",
    image: "https://www.loremfaces.net/96/id/3.jpg",
  },
  {
    id: "4",
    name: "Barry",
    image: "https://www.loremfaces.net/96/id/4.jpg",
  },
  {
    id: "5",
    name: "Diana",
    image: "https://www.loremfaces.net/96/id/5.jpg",
  },
  {
    id: "6",
    name: "Agie",
    image: "https://www.loremfaces.net/96/id/1.jpg",
  },
  {
    id: "7",
    name: "Tobi",
    image: "https://www.loremfaces.net/96/id/2.jpg",
  },
];

const transactions = [
  {
    id: "txn_001",
    type: "earning",
    amount: 5000,
    jobTitle: "Mow Lawn in Lekki",
    counterparty: "John Doe",
    status: "completed",
    method: "wallet",
    date: "2025-10-25T10:30:00Z",
    note: "Payment received for completing lawn mowing job",
  },
  {
    id: "txn_002",
    type: "payment",
    amount: 3000,
    jobTitle: "Clean Front Yard",
    counterparty: "Aisha Bello",
    status: "completed",
    method: "bank transfer",
    date: "2025-10-24T14:10:00Z",
    note: "Paid worker for yard cleaning service",
  },
  {
    id: "txn_003",
    type: "withdrawal",
    amount: 8000,
    jobTitle: "Withdrawal",
    counterparty: null,
    status: "completed",
    method: "bank transfer",
    date: "2025-10-23T09:00:00Z",
    note: "Withdrew earnings to bank account",
  },
  {
    id: "txn_004",
    type: "earning",
    amount: 2000,
    jobTitle: "Water Garden Plants",
    counterparty: "Chinedu Okeke",
    status: "pending",
    method: "wallet",
    date: "2025-10-27T09:15:00Z",
    note: "Awaiting client confirmation",
  },
  {
    id: "txn_005",
    type: "withdrawal",
    amount: 2500,
    jobTitle: "Withdrawal",
    counterparty: null,
    status: "failed",
    method: "bank transfer",
    date: "2025-10-26T08:45:00Z",
    note: "Withdrawal failed due to network issue",
  },
  {
    id: "txn_006",
    type: "payment",
    amount: 1500,
    jobTitle: "Wash Car",
    counterparty: "Michael Ade",
    status: "completed",
    method: "cash",
    date: "2025-10-23T17:05:00Z",
    note: "Paid cleaner after job completion",
  },
  {
    id: "txn_007",
    type: "earning",
    amount: 4500,
    jobTitle: "Fix Broken Door",
    counterparty: "Tunde Johnson",
    status: "completed",
    method: "bank transfer",
    date: "2025-10-22T11:00:00Z",
    note: "Received payment for carpentry job",
  },
  {
    id: "txn_008",
    type: "withdrawal",
    amount: 6000,
    jobTitle: "Withdrawal",
    counterparty: null,
    status: "completed",
    method: "bank transfer",
    date: "2025-10-21T12:00:00Z",
    note: "Funds withdrawn to GTBank account",
  },
  {
    id: "txn_009",
    type: "payment",
    amount: 4000,
    jobTitle: "Wash Windows",
    counterparty: "Blessing Eze",
    status: "completed",
    method: "cash",
    date: "2025-10-28T16:30:00Z",
    note: "Paid after completion of window washing",
  },
  {
    id: "txn_010",
    type: "earning",
    amount: 7000,
    jobTitle: "Deep Clean Apartment",
    counterparty: "Chioma Nnaji",
    status: "completed",
    method: "bank transfer",
    date: "2025-10-19T09:40:00Z",
    note: "Full payment received after job verification",
  },
];

const categories = [
  { name: "All", value: "all" },
  {
    name: "Flat",
    value: "flat",
  },
  {
    name: "House",
    value: "house",
  },
  {
    name: "Apartment",
    value: "apartment",
  },
  {
    name: "Villa",
    value: "villa",
  },
];

const recommendations = [
  {
    id: "1",
    title: "Modern 3-Bedroom Apartment in Lekki Phase 1",
    price: 3500000,
    type: "For Rent",
    bedrooms: 3,
    bathrooms: 2,
    area: "120 sqm",
    location: "Lekki Phase 1, Lagos",
    image:
      "https://www.goldcoastprivateapartments.com.au/wp-content/uploads/2023/05/Modern-3-Bedroom-Apartment-jpg-1020x680.webp",
    rating: 4.8,
    features: ["Swimming Pool", "24/7 Security", "Furnished", "Parking Space"],
    category: "Apartment",
    isLiked: false,
  },
  {
    id: "2",
    title: "Luxury 5-Bedroom Duplex with Sea View",
    price: 120000000,
    type: "For Sale",
    bedrooms: 5,
    bathrooms: 5,
    area: "480 sqm",
    location: "Banana Island, Lagos",
    image:
      "https://propscout.co.ke/storage/properties/files/modern-3-bedroom-apartment-plus-dsq-to-let-in-kilimani-s8l1o.jpg",
    rating: 4.9,
    features: ["Ocean View", "Gym", "Smart Home", "Private Pool"],
    category: "House",
    isLiked: true,
  },
  {
    id: "3",
    title: "Affordable 1-Bedroom Mini Flat",
    price: 450000,
    type: "For Rent",
    bedrooms: 1,
    bathrooms: 1,
    area: "45 sqm",
    location: "Yaba, Lagos",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.2,
    features: ["Water Heater", "Kitchenette", "Gated Compound"],
    category: "Flat",
    isLiked: false,
  },
  {
    id: "4",
    title: "Spacious 4-Bedroom Detached Duplex",
    price: 65000000,
    type: "For Sale",
    bedrooms: 4,
    bathrooms: 4,
    area: "350 sqm",
    location: "Gwarinpa, Abuja",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.7,
    features: ["BQ", "Fitted Kitchen", "Balcony", "CCTV"],
    category: "House",
    isLiked: true,
  },
  {
    id: "5",
    title: "Cozy Studio Apartment in City Center",
    price: 280000,
    type: "For Rent",
    bedrooms: 0,
    bathrooms: 1,
    area: "30 sqm",
    location: "Ikeja, Lagos",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.4,
    features: ["Furnished", "Wi-Fi", "AC", "24/7 Power"],
    category: "Apartment",
    isLiked: false,
  },
  {
    id: "6",
    title: "Elegant 2-Bedroom Terrace House",
    price: 2300000,
    type: "For Rent",
    bedrooms: 2,
    bathrooms: 2,
    area: "90 sqm",
    location: "Wuse 2, Abuja",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.6,
    features: ["Security Gate", "Parking", "Garden"],
    category: "Apartment",
    isLiked: false,
  },
  {
    id: "7",
    title: "Classic 3-Bedroom Bungalow with Large Compound",
    price: 40000000,
    type: "For Sale",
    bedrooms: 3,
    bathrooms: 3,
    area: "220 sqm",
    location: "Port Harcourt, Rivers",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.5,
    features: ["Spacious Compound", "Borehole Water", "Fenced"],
    isLiked: true,
  },
  {
    id: "8",
    title: "Serviced 1-Bedroom Apartment",
    price: 950000,
    type: "For Rent",
    bedrooms: 1,
    bathrooms: 1,
    area: "55 sqm",
    location: "Victoria Island, Lagos",
    image: "https://bestinvest.com.tr/wp-content/uploads/2024/01/DSC_7459.jpg",
    rating: 4.8,
    features: ["Gym Access", "24hr Power", "Smart Locks"],
  },
  {
    id: "9",
    title: "Mini Estate of 4 Units of 3-Bedroom Flats",
    price: 180000000,
    type: "For Sale",
    bedrooms: 12,
    bathrooms: 12,
    area: "1200 sqm",
    location: "Enugu City, Enugu",
    image: "https://example.com/images/enugu-estate.jpg",
    rating: 4.9,
    features: ["Borehole", "Parking Lot", "Security Post"],
  },
  {
    id: "10",
    title: "Compact 2-Bedroom Apartment Near Market",
    price: 700000,
    type: "For Rent",
    bedrooms: 2,
    bathrooms: 1,
    area: "60 sqm",
    location: "Oshodi, Lagos",
    image: "https://example.com/images/oshodi-flat.jpg",
    rating: 4.1,
    features: ["Accessible Road", "Kitchen", "Balcony"],
  },
];

export {
  userData,
  jobs,
  jobCategories,
  locations,
  WAL_BAL,
  sentApplicationsList,
  applicants,
  transactions,
  categories,
  recommendations,
};
