name: Build APK on Push

on:
  push:
    branches:
      - main

jobs:
  build_android_apk:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: apk # tells EAS to use your apk build profile
